name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Vercel Deployment Status
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://www.frontendobserver.com/
            https://www.frontendobserver.com/blog
            https://www.frontendobserver.com/blog/how-to-create-a-generic-automatically-generating-slug-field-for-payload-cms
            https://www.frontendobserver.com/blog/how-to-create-a-generic-fully-typed-icon-field-in-payload-cms
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true