name: Screenshot Capture - Showcase

on:
  repository_dispatch:
    types: [screenshot]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate API Secret
        env:
          API_SECRET: ${{ secrets.API_SECRET }}
          RECEIVED_SECRET: ${{ github.event.client_payload.API_SECRET }}
        run: |
          if [ "$API_SECRET" != "$RECEIVED_SECRET" ]; then
            echo "Unauthorized request: Invalid secret"
            exit 1
          fi
          echo "Request authenticated successfully"

  capture-screenshot:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install @playwright/test node-fetch

      - name: Take Screenshot and Send API Request
        env:
          API_URL: 'https://frontendobserver.com/api/payload-jobs/run'
          API_TOKEN: ${{ secrets.API_TOKEN }}
          PAGE_URL: ${{ github.event.client_payload.url }}
        run: |
          node << 'EOF'
          import { chromium } from '@playwright/test';
          import fetch from 'node-fetch';

          (async () => {
            try {
              const apiUrl = process.env.API_URL;
              const apiToken = process.env.API_TOKEN;
              const pageUrl = process.env.PAGE_URL;

              if (!apiUrl || !apiToken || !pageUrl) {
                throw new Error("Missing API_URL, API_TOKEN, or PAGE_URL environment variables.");
              }

              console.log("Launching browser...");
              const browser = await chromium.launch();
              const page = await browser.newPage();
              await page.setViewportSize({ width: 1920, height: 1080 });

              console.log("Navigating to:", pageUrl);
              await page.goto(pageUrl, { waitUntil: 'networkidle' });

              console.log("Taking screenshot...");
              const screenshotBuffer = await page.screenshot({ type: 'png' });
              await browser.close();

              const imageBase64 = screenshotBuffer.toString('base64');

              console.log("Sending API request...");
              const response = await fetch(apiUrl, {
                method: 'POST',  // Changed from GET to POST to support sending data
                headers: {
                  'Authorization': `Bearer ${apiToken}`,
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                  showcase: "createAndUpdateMediaWorkflow",
                  input: {
                    image: imageBase64,
                  },
                }),
              });

              if (!response.ok) {
                throw new Error(`API request failed: ${response.status} ${response.statusText}`);
              }

              console.log("API request successful.");
            } catch (error) {
              console.error("Error:", error.message);
              process.exit(1);
            }
          })();
          EOF