name: Showcase Jobs

on:
  repository_dispatch:
    types: [screenshot]

jobs:
  authenticate-request:
    runs-on: ubuntu-latest

    steps:
      - name: Validate API Secret
        env:
          THIRD_PARTY_API_KEY: ${{ secrets.THIRD_PARTY_API_KEY }}
          RECEIVED_SECRET: ${{ github.event.client_payload.THIRD_PARTY_API_KEY }}
        run: |
          if [ "$THIRD_PARTY_API_KEY" != "$RECEIVED_SECRET" ]; then
            echo "Unauthorized request: Invalid secret"
            exit 1
          fi
          echo "Request authenticated successfully"

  capture-screenshot:
    runs-on: ubuntu-latest
    needs: authenticate-request

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install @playwright/test && npx playwright install

      - name: Take Screenshot
        env:
          PAGE_URL: ${{ github.event.client_payload.url }}
        run: |
          node << 'EOF'
          const { chromium } = require('@playwright/test');
          const fs = require('fs');

          (async () => {
            try {
              const pageUrl = process.env.PAGE_URL;
              if (!pageUrl) throw new Error("PAGE_URL is missing");

              console.log("Launching browser...");
              const browser = await chromium.launch();
              const page = await browser.newPage();
              await page.setViewportSize({ width: 1920, height: 1080 });

              console.log("Navigating to:", pageUrl);
              await page.goto(pageUrl, { waitUntil: 'networkidle' });

              console.log("Taking screenshot...");
              const screenshotPath = 'screenshot.png';
              await page.screenshot({ path: screenshotPath, type: 'png' });
              await browser.close();

              console.log("Screenshot saved:", screenshotPath);
            } catch (error) {
              console.error("Error:", error.message);
              process.exit(1);
            }
          })();
          EOF

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot
          path: screenshot.png

  trigger-job:
    runs-on: ubuntu-latest
    needs: capture-screenshot

    steps:
      - name: Download Screenshot Artifact
        uses: actions/download-artifact@v4
        with:
          name: screenshot
          path: screenshot.png

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Send API Request
        env:
          API_URL: 'https://www.frontendobserver.com/api/payload-jobs'
          THIRD_PARTY_API_KEY: ${{ secrets.THIRD_PARTY_API_KEY }}
          SHOWCASE_ID: ${{ github.event.client_payload.showcaseID }}
        run: |
          node << 'EOF'
          const { randomUUID } = require('crypto');
          const fs = require('fs');
          const path = require('path');

          (async () => {
            try {
              const screenshotBuffer = path.resolve('./screenshot.png').toString("base64");
              const uuid = randomUUID();

              if (!fs.existsSync(screenshotBuffer)) {
                throw new Error(`Screenshot file not found: ${screenshotBuffer}`);
              }

              console.log("Sending API request...");
              const responseWorkflow = await fetch(process.env.API_URL, {
                method: 'POST',
                headers: {
                  'Authorization': `third-party API-Key ${process.env.THIRD_PARTY_API_KEY}`,
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                  workflow: "createAndUpdateMediaWorkflow",
                  input: {
                    showcaseID: `${process.env.SHOWCASE_ID}`,
                    buffer: screenshotBuffer,
                    filename: uuid,
                  },
                }),
              });

              if (!responseWorkflow.ok) {
                throw new Error(`API request failed: ${responseWorkflow.status} ${responseWorkflow.statusText}`);
              }

              const responseJob = await fetch(`${process.env.API_URL}/run`, {
                method: 'GET',
                headers: {
                  'Authorization': `third-party API-Key ${process.env.THIRD_PARTY_API_KEY}`,
                },
              });

              if (!responseJob.ok) {
                throw new Error(`API request failed: ${responseJob.status} ${responseJob.statusText}`);
              }

              console.log("API request successful.");
            } catch (error) {
              console.error("Error:", error.message);
              process.exit(1);
            }
          })();
          EOF
